name: Noisem
description: "An android app to edit images retro style"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter: ^6.0.3
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  image_gallery_saver: ^2.0.3
  image: ^4.1.3
  nes_ui: ^0.20.0
  posthog_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/cubes/
    - assets/cubes/fuji/
    - assets/cubes/kodak/
    - assets/cubes/agfa/
    - assets/cubes/ilford/
    - assets/cubes/others/
  fonts:
      - family: PressStart2P
        fonts:
          - asset: "assets/PressStart2P-Regular.ttf"
      